tasks:
  - init: |
      make install-pre-commit
      pip install --no-deps -e .
  - command: |
      cd ..
      yes spaceflights | kedro new -s spaceflights

# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
