image: gitpod/workspace-python-3.8:2023-05-08-21-16-55  # make build-docs only work on 3.8 because of certain datasets

tasks:
  # We want packages installed during the pre-build init steps to go to /workspace
  # rather than ~ so that they are persisted. Gitpod sets PIP_USER=yes to ensure this,
  # but pre-commit requires PIP_USER=no. Hence we set PIP_USER=no and use
  # pip install --user to install to /workspace.
  - name: kedro
    # before: |
    #   echo PIP_USER=no >> ~/.bashrc && export PIP_USER=no
    init: |
      make sign-off
      pip install -e /workspace/kedro
      cd /workspace
      yes project | kedro new -s pandas-iris --checkout main
      pip install -r /workspace/kedro/test_requirements.txt
      cd /workspace/kedro
      pre-commit install --install-hooks

    command: |
      clear
      kedro info

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
