tasks:
  - init: |
      python -m venv /workspace/envs/kedro --copies --system-site-packages
      source /workspace/envs/kedro/bin/activate
      make install-pre-commit
      python -m venv /workspace/envs/spaceflights --copies --system-site-packages
      source /workspace/envs/spaceflights/bin/activate
      pip install -e .
      cd ..
      yes spaceflights | kedro new -s spaceflights
      cd spaceflights
      pip install -r src/requirements.txt
  - command: |
      kedro info

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
