[tool.coverage.report]
fail_under = 100
show_missing = true
omit = [
  "kedro/template*",
  "kedro/extras/datasets/spark/*",
  "tests/extras/datasets/spark/*",
  "kedro/hooks/specs.py"
]
exclude_lines = ["pragma: no cover", "raise NotImplementedError", "SKIP_IF_NO_SPARK"]
