[tool.coverage.report]
fail_under = 100
show_missing = true
omit = [
  "kedro/templates/*",
  "kedro/extras/datasets/spark/*",
  "tests/extras/datasets/spark/*",
  "kedro/hooks/specs.py",
  "tests/*",
  "kedro/__main__.py",
  "kedro/__init__.py",
  "kedro/*/__init__.py",
]
exclude_lines = ["pragma: no cover", "raise NotImplementedError", "pass", "SKIP_IF_NO_SPARK"]
