name: Run all checks on Kedro

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "docs/**"
      - '**.md'
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "docs/**"
      - '**.md'

jobs:
  unit-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    uses: ./.github/workflows/unit-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  lint:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]
    uses: ./.github/workflows/lint.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  e2e-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    uses: ./.github/workflows/e2e-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  pip-compile:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    uses: ./.github/workflows/pip-compile.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
