name: Run linter on Kedro Docs

on:
  push:
    branches:
      - main
      - develop
      - try-ga-triggering
      - docs-only-check-for-releasemd
      - try-ga-triggering
    paths:
      - "docs/**"
      - '**.md'
  pull_request:
    branches:
      - main
      - develop
      - docs-only-check-for-releasemd
    paths:
      - "docs/**"
      - '**.md'

jobs:
  lint-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    uses: ./.github/workflows/lint.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
