name: Run e2e-tests on Kedro

on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
      branch:
        type: string
        default: ''

env:
  COLUMNS: 120
  LINES: 25

jobs:
  e2e-tests:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Set up Python ${{inputs.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{inputs.python-version}}
      - name: Cache python packages for Linux
        if: inputs.os == 'ubuntu-latest'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{inputs.os}}-python-${{inputs.python-version}}
      - name: Cache python packages for Windows
        if: inputs.os == 'windows-latest'
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{inputs.os}}-python-${{inputs.python-version}}
      - name: Add MSBuild to PATH
        if: inputs.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1
      - name: Set up Hadoop binary
        if: inputs.os == 'windows-latest'
        run: |
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest "https://github.com/steveloughran/winutils/raw/master/hadoop-2.6.3/bin/winutils.exe" -OutFile "winutils.exe" -UseBasicParsing
          New-Item -ItemType directory -Path "C:\hadoop\bin" -Force
          Move-Item -Path ".\winutils.exe" -Destination "C:\hadoop\bin"
          [Environment]::SetEnvironmentVariable("HADOOP_HOME", "C:\hadoop\", [EnvironmentVariableTarget]::Machine)
          echo "HADOOP_HOME=C:\hadoop\" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: powershell
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          make install-test-requirements
          make install-pre-commit
      - name: pip freeze
        run: pip freeze
      - name: Run e2e tests
        run: make e2e-tests
