name: Run checks on Kedro

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

jobs:
  unit-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    uses: ./.github/workflows/unit-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  lint-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.8" ]
    uses: ./.github/workflows/lint-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  e2e-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    uses: ./.github/workflows/e2e-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
