name: Label PRs
# This workflow is a part of the sync and merge job, it labels the PRs created by `sync.yml`
# workflows with the "automerge" label. This label is used by the `auto-merge-prs.yml` workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop


jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Label PR with "automerge"
        uses: actions/labeler@v5
