name: Label PRs
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop


jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Label PR with "automerge"
        uses: actions/labeler@v5
