name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    # Restrict permissions of the GITHUB_TOKEN.
    # Docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        # NOTE: v1 is updated to reflect the latest v1.x.y. Please use any tag/branch that suits your needs:
        #       https://github.com/upsidr/merge-gatekeeper/tags
        #       https://github.com/upsidr/merge-gatekeeper/branches
        uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 1800
          interval: 30
          ignored: 'ci/circle: win_e2e_tests-3.7,ci/circle: win_pip_compile-3.9,ci/circle: win_e2e_tests-3.9,ci/circle: win_pip_compile-3.8,ci/circle: lint-3.7,ci/circle: win_pip_compile-3.7,ci/circle: pip_compile-3.7,ci/circle: e2e_tests-3.7,ci/circle: win_unit_tests-3.7,ci/circle: win_unit_tests-3.9,ci/circle: e2e_tests-3.8,ci/circle: win_unit_tests-3.10,ci/circle: win_pip_compile-3.10,ci/circle: win_unit_tests-3.8,ci/circle: e2e_tests-3.9,ci/circle: unit_tests-3.10,ci/circle: unit_tests-3.8,ci/circle: e2e_tests-3.10,ci/circle: lint-3.8,ci/circle: unit_tests-3.9,ci/circle: unit_tests-3.7,ci/circle: win_e2e_tests-3.10,ci/circle: pip_compile-3.8,ci/circle: pip_compile-3.10,ci/circle: win_e2e_tests-3.8,ci/circle: lint-3.9,ci/circle: pip_compile-3.9,ci/circle: lint-3.10,build_code,ci/circleci: check-updated-files,regular'
