name: Run unit-tests on Kedro

on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
jobs:
  unit-tests:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{inputs.python-version}}
        uses: actions/setup-python@v3
        with:
          python-version: ${{inputs.python-version}}
      - name: Cache python packages for Linux
        if: inputs.os == 'ubuntu-latest'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{inputs.os}}-python-${{inputs.python-version}}
      - name: Cache python packages for Windows
        if: inputs.os == 'windows-latest'
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{inputs.os}}-python-${{inputs.python-version}}
      - name: Add MSBuild to PATH
        if: inputs.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1
      - name: Install dependencies
        run: |
            make install-test-requirements
            make install-pre-commit
      - name: Install pytables (only for windows)
        if: inputs.os == 'windows-latest'
        run: pip install tables
      - name: pip freeze
        run: pip freeze
      - name: Run unit tests
        if: inputs.os == 'ubuntu-latest'
        run: make test
      - name: Run unit tests without spark (Windows)
        if: inputs.os == 'windows-latest'
        run: make test-no-spark
